export default {
  binance: {
    production: {
      spotAPI: '"https://api.binance.com/api',
      futuresAPI: 'https://fapi.binance.com/fapi/',
      spotWS: 'wss://stream.binance.com:9443/ws',
      futuresWS: 'wss://fstream.binance.com/ws'
    },
    testnet: {
      spotAPI: '',
      futuresAPI: '',
      spotWS: '',
      futuresWS: ''
    },
  },
  updateIntervalInMillis: 20000,
  databaseName: 'lickHunterDb',
  apiServicePort: 3300,
  httpServicePort: 8888,
  httpServiceIp: 'localhost',
  futuresQuoteAsset: 'USDT',
  futuresLeverage: 5, // 0-125
  futuresMarginType: 'ISOLATED', // ISOLATED or CROSSED,
  setLeverageOnBoot: false,
  setMarginTypeOnBoot: false,
  takeProfit: 0.3,
  maxPositions: 1,
  activeSymbols: [
    'BTCUSDT',
    'ETHUSDT',
    'BCHUSDT',
    'XRPUSDT',
    'EOSUSDT',
    'LTCUSDT',
    'TRXUSDT',
    'ETCUSDT',
    'LINKUSDT',
    'XLMUSDT',
    'ADAUSDT',
    'XMRUSDT',
    'DASHUSDT',
    'ZECUSDT',
    'XTZUSDT',
    'BNBUSDT',
    'ATOMUSDT',
    'ONTUSDT',
    'IOTAUSDT',
    'BATUSDT',
    'VETUSDT',
    'NEOUSDT',
    'QTUMUSDT',
    'IOSTUSDT',
    'THETAUSDT',
    'ALGOUSDT',
    'ZILUSDT',
    'KNCUSDT',
    'ZRXUSDT',
    'COMPUSDT',
    'OMGUSDT',
    'DOGEUSDT',
    'SXPUSDT',
    'KAVAUSDT',
    'BANDUSDT',
    'RLCUSDT',
    'WAVESUSDT',
    'MKRUSDT',
    'SNXUSDT',
    'DOTUSDT',
    'YFIUSDT',
    'BALUSDT',
    'CRVUSDT',
    'TRBUSDT',
    'YFIIUSDT',
    'RUNEUSDT',
    'SUSHIUSDT',
    'SRMUSDT',
    'BZRXUSDT',
    'EGLDUSDT',
    'SOLUSDT',
    'ICXUSDT',
    'STORJUSDT',
    'BLZUSDT',
    'UNIUSDT',
    'AVAXUSDT',
    'FTMUSDT',
    'HNTUSDT',
    'ENJUSDT',
    'FLMUSDT',
    'TOMOUSDT',
    'RENUSDT',
    'KSMUSDT',
    'NEARUSDT',
    'AAVEUSDT',
    'FILUSDT',
    'RSRUSDT',
    'LRCUSDT',
    'MATICUSDT',
    'OCEANUSDT',
    'CVCUSDT',
    'BELUSDT',
    'CTKUSDT',
    'AXSUSDT',
    'ALPHAUSDT',
    'ZENUSDT',
    'SKLUSDT',
    'GRTUSDT',
    '1INCHUSDT',
    'AKROUSDT',
    'CHZUSDT',
    'SANDUSDT',
    'ANKRUSDT',
    'LUNAUSDT',
    'BTSUSDT',
    'LITUSDT',
    'UNFIUSDT',
    'DODOUSDT',
    'REEFUSDT',
    'RVNUSDT',
    'SFPUSDT',
    'XEMUSDT',
    'BTCSTUSDT',
    'COTIUSDT',
    'CHRUSDT',
    'MANAUSDT',
    'ALICEUSDT',
  ]
}
